In [46]:
from numpy import random
def load_data(negative, positive):
    returnval = []
    with open(negative) as file1:
        content2 = file1.read().replace("\n", " ").split(">")
        content = [a.split(" ", 1) for a in content2]
        for a in content[1:]:
            if a != "" and a!= [""] and a != []:
                returnval.append([a[0], a[1].replace(" ", ""), 0])
    with open(positive) as file2:
        content2 = file2.read().replace("\n", " ").split(">")
        content = [a.split(" ", 1) for a in content2][:1000]
        for a in content[1:]:
            if a != "" and a != [""] and a != []:
                returnval.append([a[0], a[1].replace(" ", ""), 1])
    #random.shuffle(returnval,random.random)
    return returnval

In [47]:
dataset = load_data("dataSet/protein_neg.txt","dataSet/protein_pos.txt")

In [48]:
#print (dataset)
for data in dataset:
    print (data)

['1RQWA', 'ATFEIVNRCSYTVWAAASKGDAALDAGGRQLNSGESWTINVEPGTKGGKIWARTDCYFDDSGSGICKTGDCGGLLRCKRFGRPPTTLAEFSLNQYGKDYIDISNIKGFNVPMDFSPTTRGCRGVRCAADIVGQCPAKLKAPGGGCNDACTVFQTSEYCCTTGKCGPTEYSRFFKRLCPDAFSYVLDKPTTVTCPGSSNYRVTFCPTA', 0]
['1H2GB', 'SNMWVIGKSKAQDAKAIMVNGPQFGWYAPAYTYGIGLHGAGYDVTGNTPFAYPGLVFGHNGVISWGSTAGLGDDVDIFAERLSAEKPGYYLHNGKWVKMLSREETITVKNGQAETFTVWRTVHGNILQTDQTTQTAYAKSRAWDGKEVASLLAWTHQMKAKNWQEWTQQAAKQALTINWYYADVNGNIGYVHTGAYPDRQSGHDPRLPVPGTGKWDWKGLLPFEMNPKVYNPQSGYIANWNNSPQKDYPASDLFAFLWGGADRVTEIDRLLEQKPRLTADQAWDVIRQTSRQDLNLRLFLPTLQAATSGLTQSDPRRQLVETLTRWDGINLLNDDGKTWQQPGSAILNVWLTSMLKRTVVAAVPMPFDKWYSASGYETTQDGPTGSLNISVGAKILYEAVQGDKSPIPQAVDLFAGKPQQEVVLAALEDTWETLSKRYGNNVSNWKTPAMALTFRANNFFGVPQAAAEETRHQAEYQNRGTENDMIVFSPTTSDRPVLAWDVVAPGQSGFIAPDGTVDKHYEDQLKMYENFGRKSLWLTKQDVEAHKESQEVLHVQR', 0]
['1A12A', 'RRSPPADAIPKSKKVKVSHRSHSTEPGLVLTLGQGDVGQLGLGENVMERKKPALVSIPEDVVQAEAGGMHTVCLSKSGQVYSFGCNDEGALGRDTSVEGSEMVPGKVELQEKVVQVSAGDSHTAALTDDGRVFLWGSFRDNNGVIGLLEPMKKSMVPVQVQLDVPVVKVASGNDHLVMLTADGDLYTLGCG

['3M03C', 'MSNIGIRDLAVQFSCIEAVNMASKILKSYESSLPQTQQVDLDLSRPLFTSAALLSACKILKLKVDKNKMVATSGVKKAIFDRLCKQLEKIGQQVD', 1]
['3M8EB', 'MGSSHHHHHHSSGLVPRGSHMNRDHFYTLNIAEIAERIGNDDCAYQVLMAFINENGEAQMLNKTAVAEMIQLSKPTVFATVNSFYCAGYIDETRVGRSKIYTLSDLGVEIVECFKQKAMEMRNL', 1]
['3MAJA', 'GHMDVGERSSDQGTTVLTEAQRIDWMRLIRAENVGPRTFRSLINHFGSARAALERLPELARRGGAARAGRIPSEDEARREIEAGRRIGVELVAPGETGYPTRLATIDDAPPLLGVHALPEALAVMARPMIAIVGSRNASGAGLKFAGQLAADLGAAGFVVISGLARGIDQAAHRASLSSGTVAVLAGGHDKIYPAEHEDLLLDIIQTRGAAISEMPLGHVPRGKDFPRRNRLISGASVGVAVIEAAYRSGSLITARRAADQGREVFAVPGSPLDPRAAGTNDLIKQGATLITSASDIVEAVASILERPIELPGREPEHAPPEGEPDTGDRTRILALLGPSPVGIDDLIRLSGISPAVVRTILLELELAGRLERHGGSLVSLS', 1]
['3MKYB', 'MGSSHHHHHHSSGLVPRGSHYRPTSAYERGQRYASRLQNEFAGNISALADAENISRKIITRCINTAKLPKSVVALFSHPGELSARSGDALQKAFTDKEELLKQQASNLHEQKKAGVIFEADEVITLLTSVLKTSSASRTSLSSRHQFAPGATVLYKGDKMVLNLDRSRVPTECIEKIEAILKELEKPAP', 1]
['3MU6D', 'GRKKIQITRIMDERNRQVTFTKRKFGLMKKAYELSVLCDCEIALIIFNSSNKLFQYASTDMDKVLLKYTAY', 1]
['3MUJB', 'SMEATPCIKAISPSEGWTTGGATVIIIGDNFFDGLQVVFGTML

In [49]:
import csv
with open("base_feature/raw_data_all.csv","w+",newline='') as csvfile:
    writer = csv.writer(csvfile)
    for data in dataset:
        writer.writerow(data)

In [50]:
def get_base_frequencies(seq):
    return [ seq.count(base)/len(seq)
        for base in 'ATGC']

In [53]:
with open("base_feature/raw_data_all.csv","r+") as csvfile:
    reader = csv.reader(csvfile)
    for line in reader:
        frequencies = get_base_frequencies(line[1])
        with open("base_feature/feature_ATGC_freq.csv","a+",newline='') as file:
            writer = csv.writer(file)
            writer.writerow(frequencies)

测试下仅仅在base feature条件下准确率

In [54]:
import codecs
from itertools import *
import numpy as np

In [55]:
def load_data(filename):
    file = codecs.open(filename,'r','utf-8')
    data = []
    label = []
    for line in islice(file,0,None):
        line = line.strip().split(',')
        #print ("reading data....")
        data.append([float(i) for i in line[0:-1]])
        label.append(line[-1])
    x = np.array(data)
    y = np.array(label)
    print (x)
    print (y)
    return x,y

In [56]:
import pylab as pl
from itertools import *
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [57]:
def train(x_train,y_label):  ####为保证分类结果的准确度可靠，采用十折交叉验证
    ##########logisticRegression################
    clf1 = LogisticRegression()
    score1 = model_selection.cross_val_score(clf1,x_train,y_label,cv=10,scoring="accuracy")
    x = [int(i) for i in range(1,11)]
    y = score1
    pl.ylabel(u'Accuracy')
    pl.xlabel(u'times')
    pl.plot(x,y,label='LR')
    pl.legend()
    pl.savefig("1_LR.png")
    #pl.show()
    print ('The accuracy of LogisticRegression:')
    print (np.mean(score1))
    ###############SVM（linear)###################
    clf2 = svm.LinearSVC(random_state=2016)
    score2 = model_selection.cross_val_score(clf2,x_train,y_label,cv=10,scoring='accuracy')
    #print score2
    print ('The accuracy of linearSVM:')
    print ((np.mean(score2)))
    x = [int(i) for i in range(1, 11)]
    y = score2
    pl.ylabel(u'Accuracy')
    pl.xlabel(u'times')
    pl.plot(x, y,label='SVM')
    pl.legend()
    pl.savefig("2_SVM.png")
    #pl.show()
    #################Naive Bayes################
    clf3 = GaussianNB()
    score3 =  model_selection.cross_val_score(clf3,x_train,y_label,cv=10,scoring='accuracy')
    print ("The accuracy of Naive Bayes:")
    print ((np.mean(score3)))
    x = [int(i) for i in range(1, 11)]
    y = score3
    pl.ylabel(u'Accuracy')
    pl.xlabel(u'times')
    pl.plot(x, y,label='NB')
    pl.legend()
    pl.savefig("3_NB.png")
    #pl.show()
    ################DecidionTree###############
    clf4 = tree.DecisionTreeClassifier()
    score4 = model_selection.cross_val_score(clf4,x_train,y_label,cv=10,scoring="accuracy")
    print ('The accuracy of DB:')
    print (np.mean(score4))
    x = [int(i) for i in range(1, 11)]
    y = score4
    pl.ylabel(u'Accuracy')
    pl.xlabel(u'times')
    pl.plot(x, y,label='DB')
    pl.legend()
    pl.savefig("4_DB.png")
    #pl.show()

In [58]:
X,Y = load_data('base_feature/feature_ATGC_freq.csv')

[[ 0.07729469  0.09661836  0.11594203  0.07729469]
 [ 0.09156194  0.07540395  0.08258528  0.        ]
 [ 0.05811138  0.04600484  0.13317191  0.01937046]
 ..., 
 [ 0.14534884  0.02906977  0.10465116  0.00581395]
 [ 0.10843374  0.04149933  0.06961178  0.01338688]
 [ 0.225       0.1         0.          0.        ]]
['0' '0' '0' ..., '1' '1' '1']


In [59]:
train(X,Y)

The accuracy of LogisticRegression:
0.610124610592
The accuracy of linearSVM:
0.619496365524
The accuracy of Naive Bayes:
0.546936656282
The accuracy of DB:
0.574852890273
